title:              Blog CIT 480
email:              dontcontact@blog.com
description:        A Blog about my experience taking CIT 480
author:             Juan Delgado
baseurl:            "/newblog"
url:                "https://jjd90.github.io"

# Social Profiles
#twitter_username:   SBootstrap
github_username:    jjd90
instagram_username:  j.kenobi_
#linkedin_username:

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
